repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: golangci-lint
        entry: golangci-lint run -c .golangci.yml -v
        stages:
          - commit

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-unit-tests
        entry: go test -v ./... -tags=unit
        stages:
          - commit