apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shortly-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly-deployment
  labels:
    app: shortly
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shortly
  template:
    metadata:
      labels:
        app: shortly
    spec:
      containers:
        - name: shortly
          image: openfile/shortly:0.0.2
          volumeMounts:
            - mountPath: /.mem
              name: memory-volume
          ports:
            - containerPort: 6161
      volumes:
        - name: memory-volume
          persistentVolumeClaim:
            claimName: shortly-volume
---
apiVersion: v1
kind: Service
metadata:
  name: shortly-service
spec:
  selector:
    app: shortly
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6161
      targetPort: 6161
      nodePort: 30001
